### ISSUE TITLE
`5.0.0` does not work with `rolldown-plugin-dts`

### ISSUE THREAD

**Issue by adamhl8** [sindresorhus/type-fest#1232]
### Bug description

This might be a problem with [rolldown-plugin-dts](https://github.com/sxzz/rolldown-plugin-dts) and not type-fest, but everything works with type-fest `4.41.0` which is why I'm opening this issue here.

When bundling my project with tsdown (which uses rolldown + rolldown-plugin-dts), I get the following error:

```
[plugin rolldown-plugin-dts:generate]
RollupError: src/knip.ts(16,14): error TS2742: The inferred type of 'knipConfig' cannot be named without a reference to '../node_modules/type-fest/source/internal/type.js'. This is likely not portable. A type annotation is necessary.
src/knip.ts(16,14): error TS2742: The inferred type of 'knipConfig' cannot be named without a reference to '../node_modules/type-fest/source/merge-deep.js'. This is likely not portable. A type annotation is necessary.
```

This can be reproduced by cloning [this project](https://github.com/adamhl8/configs), updating type-fest to `5.0.0`, and running `bun tsdown`.

**Comment by sindresorhus** [comment]
From the release notes:

> This package is now pure ESM. Please [read this](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).

Which is definitely related. Not a problem with this package, but rather your bundle config.

**Comment by adamhl8** [comment]
I played around with it a bit more. This isn't a bundler-specific issue, and rolldown-plugin-dts uses tsc under the hood anyway.

Here's a simplified reproduction of the issue:

In `tsconfig.json`:
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "declaration": true
  }
}
```

In `index.ts`:
```ts
import type { MergeDeep } from "type-fest"

function createFn<T>(base: T) {
  function fn<U>(input: U): MergeDeep<T, U>
  function fn<U>(input?: U) {
    return null as any
  }
  return fn
}

export const fn = createFn({})
```

```
The inferred type of 'fn' cannot be named without a reference to '../../node_modules/type-fest/source/merge-deep'. This is likely not portable. A type annotation is necessary. (ts 2742)
```

Now, I can "fix" this by explicitly typing `fn`, but that wasn't necessary pre-5.0.0.

**Comment by AndrewSouthpaw** [comment]
Agreed this is an issue with typescript, not with ESM. We ended up patching the library on our end to re-export the helper types.
